### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by PickleNik**
don't ignore the node_modules, they need your attention

### CODE REVIEW

**Comment by PickleNik** [comment]
This resolves #3

**Comment by Hacksore** [comment]
I'm going to need a good reason here to omit `node_module`.

This seems to go against what the project aims to solve, package manager unification.

Please include some unit tests or benchmarks and I can reevaluate this proposal.

**Comment by PickleNik** [comment]
> I'm going to need a good reason here to omit `node_module`.

Markus Markiplier @markkhoo asked
Screenshot 2023-06-29 at 3 21 29 PM

**Comment by markkhoo** [comment]
Looks Bad To Me

**Comment by Hacksore** [comment]
> Looks Bad To Me

image

**Pull request closed without merging**
